language: objective-c
osx_image: xcode7.3
env:
  global:
  - PROJECT=KWDataSourceKit.xcodeproj
  - IOS_FRAMEWORK_SCHEME="KWDataSourceKit iOS"
  - TVOS_FRAMEWORK_SCHEME="KWDataSourceKit tvOS"
  - IOS_SDK=iphonesimulator9.3
  - TVOS_SDK=appletvsimulator9.2
  - IOS_EXAMPLE_SCHEME="iOS Example"
  matrix:
    - DEST_OS="8.4"          DEST_DEVICE="iPhone 5"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DEST_OS="8.4"          DEST_DEVICE="iPhone 6"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DEST_OS="9.0"          DEST_DEVICE="iPhone 5"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DEST_OS="9.1"          DEST_DEVICE="iPhone 5S"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DEST_OS="9.2"          DEST_DEVICE="iPhone 6"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DEST_OS="9.3"          DEST_DEVICE="iPhone 6S"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DEST_OS="9.2"          DEST_DEVICE="Apple TV 1080p"    SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"   BUILD_EXAMPLE="NO"    EXAMPLE_SCHEME="$TVOS_EXAMPLE_SCHEME"


before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

before_script:
- export DESTINATION="OS=$DEST_OS,name=$DEST_DEVICE"
- instruments -s devices
- export IOS_SIMULATOR_UDID=`instruments -s devices | grep "$DEST_DEVICE ($DEST_OS" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
- echo $IOS_SIMULATOR_UDID
- open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Framework in Release
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
